"""Add InfluencerProfile table

Revision ID: 44975931f62d
Revises: bdeeeb4b40e4
Create Date: 2024-08-10 07:52:19.113301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44975931f62d'
down_revision = 'bdeeeb4b40e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influencer_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niche', sa.String(length=100), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('influencer_profile')
    # ### end Alembic commands ###
