"""Update InfluencerProfile relationship

Revision ID: c9383b883de0
Revises: e3127b7d73d7
Create Date: 2024-08-10 08:49:14.331203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9383b883de0'
down_revision = 'e3127b7d73d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencer_profile', schema=None) as batch_op:
        batch_op.alter_column('niche',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('reach',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencer_profile', schema=None) as batch_op:
        batch_op.alter_column('reach',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('niche',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###
