"""Add InfluencerProfile table

Revision ID: dc3cf1aa0592
Revises: 44975931f62d
Create Date: 2024-08-10 08:41:03.946555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3cf1aa0592'
down_revision = '44975931f62d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencer_profile', schema=None) as batch_op:
        batch_op.alter_column('niche',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('reach',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencer_profile', schema=None) as batch_op:
        batch_op.alter_column('reach',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('niche',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
