"""Update InfluencerProfile relationship

Revision ID: e3127b7d73d7
Revises: dc3cf1aa0592
Create Date: 2024-08-10 08:44:29.938533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3127b7d73d7'
down_revision = 'dc3cf1aa0592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencer_profile', schema=None) as batch_op:
        batch_op.alter_column('niche',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               nullable=False)
        batch_op.alter_column('reach',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencer_profile', schema=None) as batch_op:
        batch_op.alter_column('reach',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('niche',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
